### ISSUE TITLE
Two different margins between the paragraphs

### ISSUE THREAD

**Issue by mattdwen** [tyesamson/the-finishing-suite#2]

**Comment by mattdwen** [comment]
Fixed with code tidy.

**Comment by tyesamson** [comment]
still present in what i'm looking at sorry 

https://i.imgur.com/CQu8Ync.jpg
